# Generated by Django 6.0.4 on 2026-04-24 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(default='sample@gamil.com', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
